# Generated by Django 4.2.6 on 2023-10-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('Syrup', 'Syrup'), ('Tablet', 'Tablet'), ('Vitamin', 'Vitamin'),], max_length=50)),
                ('picture', models.ImageField(upload_to='Medicine')),
                ('amount', models.IntegerField()),
                ('discount_amount', models.IntegerField()),
            ],
        ),
    ]
