# Generated by Django 4.2.6 on 2023-11-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
